name: Sync to Hugging Face Spaces

on:
  push:
    branches: [seydna]

jobs:
  sync-to-hub:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Push to HF Spaces
        env:
          HF_TOKEN: ${{ secrets.HF_TOKEN }}
        run: |
          git push https://seydnaaly:$HF_TOKEN@huggingface.co/spaces/seydnaaly/mauripay-backend HEAD:main --force
